name: Commentary sepration

on:
  push:
    branches: [ master ]

jobs:
  transform:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
#         python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 1 # Because of this, you will fail to push refs to dest repo
    - name: Checkout Processed files
      uses: actions/checkout@master
      with:
        repository: sanskrit/ashtadhyayi_com_transforms
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        path: processed_data
        fetch-depth: 1 # Because of this, you will fail to push refs to dest repo
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install git+https://github.com/sanskrit-coders/doc_curation/@master -U
        python -m pip install git+https://github.com/ashtadhyayi/data_curation@master -U
    - name: Create local changes
      run: |
        rm -rf `pwd`/processed_data/*
        python -c "from ashtadhyayi_data.reader.ashtadhyayi_com import transformer; transformer.separate_commentaries(indir=\"`pwd`/sutraani\", outdir=\"`pwd`/processed_data/sUtra-commentaries/\", dry_run=False)"
    - name: Commit files
      run: |
        cd processed_data
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --all
        echo "https://github.com/ashtadhyayi-com/data/runs/$GITHUB_RUN_ID" > current_run.txt
        git diff-index --quiet HEAD || git commit -m "Add changes" -a
        cd ..
      # We want to ensure that there is some change in processed_data for every change in ashtadhyayi data - so that downstream listeners can hark to the corresponding trigger.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.VISH_TOKEN }}
        repository: sanskrit/ashtadhyayi_com_transforms
        branch: processed_data
        directory: processed_data
#        force: true